### ISSUE TITLE
error when I compile on NodeMCU 1.0

### ISSUE THREAD

**Issue by ivanpiffer** [tobiasschuerg/ESP8266_Influx_DB#12]
this is the message using the example "writing_single"

InfluxData.h:26:69: error: '_time' was not declared in this scope
String toString() const { return _measurement + _tags + _values + _time; }

**Comment by r4ptor** [comment]
Looks like a typo happened in InfluxData.h

In pull request #10 _time was properly replaced with _timestamp.
Either check out this branch, wait for the merge or check out the repository and manually replace _time with _timestamp in InfluxData.h line 26.
